baseURL: "https://farzy.org/"
title: "Farzad FARID"

theme:
  - "github.com/theNewDynamic/gohugo-theme-ananke"

enableEmoji: true
enableRobotsTXT: true
enableGitInfo: true
googleAnalytics: G-JTDXMGH6FP
disqusShortname: farzy-org

SectionPagesMenu: "main"

params:
  favicon: ""
  description: "On books, comics, SRE, Kubernetes…"
  facebook: ""
  twitter: "https://twitter.com/Farzy"
  instagram: "https://www.instagram.com/farzadfarid/"
  youtube: ""
  github: "https://github.com/Farzy"
  gitlab: "https://gitlab.com/farzy"
  linkedin: "https://linkedin.com/in/ffarid"
  mastodon: ""
  slack: ""
  stackoverflow: ""
  # choose a background color from any on this page: http://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class: "bg-dark-gray"
  featured_image: "/images/taira-nami-teapot.jpg"
  images:
    - "/images/taira-nami-teapot.jpg"
  recent_posts_number: 10
  show_reading_time: true
  # Explicitly list blog sections to display in main page
  mainSections:
    - books
    - misc
    - it

defaultContentLanguage: "fr"
defaultContentLanguageInSubdir: true
languages:
  en:
    languageCode: en
    languageName: English
    weight: 2
  fr:
    languageCode: fr-FR
    languageName: Français
    weight: 1
    title: "Site de Farzad"
    params:
      description: "Des livres, des bandes dessinées, de l'infrastructure, du Kubernetes…"
