baseURL = "https://farzy.org/"
languageCode = "fr-FR"
languageName= "Français"
title = "Farzad FARID"

theme = "ananke"

enableEmoji = true
enableRobotsTXT = true
enableGitInfo = true

SectionPagesMenu = "main"

DefaultContentLanguage = "fr"

[params]
  favicon = ""
  description = "No turn in red."
  facebook = ""
  twitter = "https://twitter.com/Farzy"
  instagram = ""
  youtube = ""
  github = "https://github.com/Farzy"
  gitlab = ""
  linkedin = "https://linkedin.com/in/ffarid"
  mastodon = ""
  slack = ""
  stackoverflow = ""
  # choose a background color from any on this page: http://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-black"
  featured_image = "/images/taira-nami-teapot.jpg"
  recent_posts_number = 4
