baseURL: "https://farzy.org/"
#languageCode: "fr"
#languageName: "Français"
title: "Farzad FARID"

theme: "ananke"

enableEmoji: true
enableRobotsTXT: true
enableGitInfo: true
googleAnalytics: UA-167419986-1
disqusShortname: farzy-org

SectionPagesMenu: "main"

params:
  favicon: ""
  description: "On books, comics, SRE, Kubernetes…"
  facebook: ""
  twitter: "https://twitter.com/Farzy"
  instagram: "https://www.instagram.com/farzadfarid/"
  youtube: ""
  github: "https://github.com/Farzy"
  gitlab: "https://gitlab.com/farzy"
  linkedin: "https://linkedin.com/in/ffarid"
  mastodon: ""
  slack: ""
  stackoverflow: ""
  # choose a background color from any on this page: http://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class: "bg-dark-gray"
  featured_image: "/images/taira-nami-teapot.jpg"
  recent_posts_number: 4
  show_reading_time: true

DefaultContentLanguage: "fr"
defaultContentLanguageInSubdir: true
languages:
  en:
    languageName: English
    weight: 2
  fr:
    languageName: Français
    weight: 1
    title: "Site de Farzad"
    description: "Des livres, des bandes dessinées, de l'infrastructure, du Kubernetes…"
